### ISSUE TITLE
Do you have plan to release your pre-trained model?

### ISSUE THREAD

**Issue by ChicoQ** [Guillem96/deep-erase#1]
What a nice work you've done. I'd like to have a try the pre-trained model if you're planning to. Many thanks.

**Comment by Guillem96** [comment]
I do not have the pretrained weights, nor I am planning to publish them.

The README file results are generated with a model trained during 2 hours in colab. So obtaining a reliable model is not that hard :)

Thanks for opening the issue, and I hope the answer helps.
